name: MiraiChat
version: ${project.version}
main: top.zhzskin.mirai.miraichat.MiraiChat
commands:
  miraichat:
    description: "向QQ群里发送消息"
    usage: "/miraichat help|reload|sendImage <图片url1> [图片url2]|sendMsg <消息>|setBroadcastGroupMessage <true|false>|setChatEnableDisableMessage <true|false>|setEventChat <true|false>|setGroup <群号>|unload" #指令的用法 当onCommand()方法返回false时提示这里的内容
    aliases: [mchat,mc]
    permission: "miraichat.use"
    permission-message: "你没有使用该指令的权限"
permissions:
  miraichat:
    use:
      description: "一个默认的权限"
      default: true
    help:
      description: "显示帮助"
      default: true
    reload:
      description: "重载配置"
      default: op
    sendImage:
      description: "发送图片"
      default: true
    sendMsg:
      description: "发送消息"
      default: true
    setBroadcastGroupMessage:
      description: "设置广播群消息"
      default: op
    setChatEnableDisableMessage:
      description: "设置启用停用消息推送"
      default: op
    setEventChat:
      description: "设置聊天事件推送"
      default: op
    setGroup:
      description: "设置群"
      default: op
    unload:
      description: "卸载"
      default: op
